CREATE TYPE 2 UNIQUE INDEX PK_PMML_OPLEV
    ON PMML_OPLEV
    (POV_ID                          ASC)
USING STOGROUP SGDB0U
     PRIQTY        -1
     SECQTY        -1
     FREEPAGE 0 PCTFREE 10
     GBPCACHE CHANGED
     CLUSTER
     COMPRESS NO
     BUFFERPOOL BP2
     CLOSE YES
     COPY NO
     DEFER NO
     DEFINE YES
     PIECESIZE 2 G;
