SET CURRENT SQLID = RLH_DB_OBJECTS_A99E01;
SET SCHEMA RLH_DB_OBJECTS_A99E01;
--
-- Triggers op colums met DOMEINwaarden; check ipv FK's die niet nauwkeurig genoeg zijn.
--
--

--#SET TERMINATOR @
--
--
  CREATE OR REPLACE TRIGGER MUBBI000
    BEFORE INSERT ON KE_META_GEGEVENS_UITGAAND_BERICHT
    REFERENCING NEW AS NEWDOM
    FOR EACH ROW
    DISABLE DEBUG MODE
    QUALIFIER knaller
    ASUTIME LIMIT 9000
    WLM ENVIRONMENT FOR DEBUG MODE RLHNOP
    CONCURRENT ACCESS RESOLUTION USE CURRENTLY COMMITTED
    DYNAMICRULES RUN
    APPLICATION ENCODING SCHEME UNICODE
    WITH EXPLAIN
    WITHOUT IMMEDIATE WRITE
    ISOLATION LEVEL CS
    RELEASE AT COMMIT
    ROUNDING DEC_ROUND_HALF_EVEN
    DECIMAL(31)
    NOT SECURED
    BUSINESS_TIME SENSITIVE YES
    SYSTEM_TIME SENSITIVE NO
    ARCHIVE SENSITIVE NO
    CONCENTRATE STATEMENTS WITH LITERALS
    WHEN(NEWDOM.EXTERN_KOPPELVLAK IS NOT NULL)
      BEGIN
        DECLARE DOMFOUND VARCHAR( 5) default NULL ;
        SELECT  DOMEIN_CODE INTO DOMFOUND FROM S_DOMEIN FOR
        BUSINESS_TIME AS OF CURRENT_DATE
          WHERE DOMEIN_CODE = NEWDOM.EXTERN_KOPPELVLAK AND DOMEIN_NAAM
          = 'Extern Koppelvlak'
        ;
        IF DOMFOUND is NULL THEN
          signal sqlstate '99DOM' set message_text =
          'Domein Extern Koppelvlak niet correct' ;
        END IF ;
      END @
--
--
--
  CREATE OR REPLACE TRIGGER MUBBU000
    BEFORE UPDATE OF EXTERN_KOPPELVLAK
    ON KE_META_GEGEVENS_UITGAAND_BERICHT
    REFERENCING NEW AS NEWDOM
    FOR EACH ROW
    DISABLE DEBUG MODE
    QUALIFIER knaller
    ASUTIME LIMIT 9000
    WLM ENVIRONMENT FOR DEBUG MODE RLHNOP
    CONCURRENT ACCESS RESOLUTION USE CURRENTLY COMMITTED
    DYNAMICRULES RUN
    APPLICATION ENCODING SCHEME UNICODE
    WITH EXPLAIN
    WITHOUT IMMEDIATE WRITE
    ISOLATION LEVEL CS
    RELEASE AT COMMIT
    ROUNDING DEC_ROUND_HALF_EVEN
    DECIMAL(31)
    NOT SECURED
    BUSINESS_TIME SENSITIVE YES
    SYSTEM_TIME SENSITIVE NO
    ARCHIVE SENSITIVE NO
    CONCENTRATE STATEMENTS WITH LITERALS
    WHEN(NEWDOM.EXTERN_KOPPELVLAK IS NOT NULL)
      BEGIN
        DECLARE DOMFOUND VARCHAR( 5) default NULL ;
        SELECT  DOMEIN_CODE INTO DOMFOUND FROM S_DOMEIN FOR
        BUSINESS_TIME AS OF CURRENT_DATE
          WHERE DOMEIN_CODE = NEWDOM.EXTERN_KOPPELVLAK AND DOMEIN_NAAM
          = 'Extern Koppelvlak'
        ;
        IF DOMFOUND is NULL THEN
          signal sqlstate '99DOM' set message_text =
          'Domein Extern Koppelvlak niet correct' ;
        END IF ;
      END @
--
--
--
------------------------------------------------------------------------    
  CREATE OR REPLACE TRIGGER MUBBI001
    BEFORE INSERT ON KE_META_GEGEVENS_UITGAAND_BERICHT
    REFERENCING NEW AS NEWDOM
    FOR EACH ROW
    DISABLE DEBUG MODE
    QUALIFIER knaller
    ASUTIME LIMIT 9000
    WLM ENVIRONMENT FOR DEBUG MODE RLHNOP
    CONCURRENT ACCESS RESOLUTION USE CURRENTLY COMMITTED
    DYNAMICRULES RUN
    APPLICATION ENCODING SCHEME UNICODE
    WITH EXPLAIN
    WITHOUT IMMEDIATE WRITE
    ISOLATION LEVEL CS
    RELEASE AT COMMIT
    ROUNDING DEC_ROUND_HALF_EVEN
    DECIMAL(31)
    NOT SECURED
    BUSINESS_TIME SENSITIVE YES
    SYSTEM_TIME SENSITIVE NO
    ARCHIVE SENSITIVE NO
    CONCENTRATE STATEMENTS WITH LITERALS
    WHEN(NEWDOM.BERICHTSOORT IS NOT NULL)
      BEGIN
        DECLARE DOMFOUND VARCHAR( 5) default NULL ;
        SELECT  DOMEIN_CODE INTO DOMFOUND FROM S_DOMEIN FOR
        BUSINESS_TIME AS OF CURRENT_DATE
          WHERE DOMEIN_CODE = NEWDOM.BERICHTSOORT AND DOMEIN_NAAM
          = 'Berichtsoort'
        ;
        IF DOMFOUND is NULL THEN
          signal sqlstate '99DOM' set message_text =
          'Domein Berichtsoort niet correct' ;
        END IF ;
      END @
--
--
--
  CREATE OR REPLACE TRIGGER MUBBU001
    BEFORE UPDATE OF BERICHTSOORT
    ON KE_META_GEGEVENS_UITGAAND_BERICHT
    REFERENCING NEW AS NEWDOM
    FOR EACH ROW
    DISABLE DEBUG MODE
    QUALIFIER knaller
    ASUTIME LIMIT 9000
    WLM ENVIRONMENT FOR DEBUG MODE RLHNOP
    CONCURRENT ACCESS RESOLUTION USE CURRENTLY COMMITTED
    DYNAMICRULES RUN
    APPLICATION ENCODING SCHEME UNICODE
    WITH EXPLAIN
    WITHOUT IMMEDIATE WRITE
    ISOLATION LEVEL CS
    RELEASE AT COMMIT
    ROUNDING DEC_ROUND_HALF_EVEN
    DECIMAL(31)
    NOT SECURED
    BUSINESS_TIME SENSITIVE YES
    SYSTEM_TIME SENSITIVE NO
    ARCHIVE SENSITIVE NO
    CONCENTRATE STATEMENTS WITH LITERALS
    WHEN(NEWDOM.BERICHTSOORT IS NOT NULL)
      BEGIN
        DECLARE DOMFOUND VARCHAR( 5) default NULL ;
        SELECT  DOMEIN_CODE INTO DOMFOUND FROM S_DOMEIN FOR
        BUSINESS_TIME AS OF CURRENT_DATE
          WHERE DOMEIN_CODE = NEWDOM.BERICHTSOORT AND DOMEIN_NAAM
          = 'Berichtsoort'
        ;
        IF DOMFOUND is NULL THEN
          signal sqlstate '99DOM' set message_text =
          'Domein Berichtsoort niet correct' ;
        END IF ;
      END @
--
--
--#SET TERMINATOR ;

