select EXTRACT(YEAR FROM current timestamp) from sysibm.sysdummy1
;

CREATE UNIQUE INDEX X02PRODUCTIESCHEMA
   ON PRODUCTIESCHEMA (EXTRACT(YEAR FROM PRODUCTIEDATUM), EXTRACT(MONTH FROM PRODUCTIEDATUM))
    USING STOGROUP SGDB0U
          PRIQTY -1
          SECQTY -1
          ERASE  NO
    BUFFERPOOL BP2
    CLOSE YES
    FREEPAGE 0
    PCTFREE  10
;
