SET CURRENT SQLID = ORAE01;
SET SCHEMA ORAE01;
GRANT SELECT, INSERT, DELETE, UPDATE ON TABLE
    MSCON_AANGIFTE_TIJDVAK,
    MSCON_BERICHT_INHOUD,
    MSCON_BETALINGSVERPLICHTING,
    MSCON_BETALINGSVERPLICHTING_AUD,
    MSCON_INKOMEND_BERICHT,
    MSCON_STAFFEL,
    MSCON_STAFFEL_AUD,
    MSCON_REVINFO,
    MSCON_UITGAAND_BERICHT,
    MSCON_QRTZ_BLOB_TRIGGERS,
    MSCON_QRTZ_CALENDARS,
    MSCON_QRTZ_CRON_TRIGGERS,
    MSCON_QRTZ_FIRED_TRIGGERS,
    MSCON_QRTZ_JOB_DETAILS,
    MSCON_QRTZ_LOCKS,
    MSCON_QRTZ_PAUSED_TRIGGER_GRPS,
    MSCON_QRTZ_SCHEDULER_STATE,
    MSCON_QRTZ_SIMPLE_TRIGGERS,
    MSCON_QRTZ_SIMPROP_TRIGGERS,
    MSCON_QRTZ_TRIGGERS
    TO $EORA61C, $EORA61C;

