CREATE LOB TABLESPACE FBDTSMZO
    IN FBDDB01
    USING STOGROUP SGDB0U
    PRIQTY -1 SECQTY -1
    ERASE  NO
    GBPCACHE CHANGED
    NOT LOGGED
    DSSIZE 16 G
    BUFFERPOOL BP9
    LOCKSIZE ANY
    LOCKMAX 0
    CLOSE YES
    COMPRESS NO
    DEFINE YES
    INSERT ALGORITHM 0;
