LOCK TABLE ZEKERHOPM IN EXCLUSIVE MODE;

SELECT ZHORELID, ZHOACTSRTCD, ZHONR, ZHOTEXT FROM FINAL TABLE(
MERGE INTO ZEKERHOPM AS OPM 
  USING (SELECT ZKHRELID, ZKHACTSRTCD, ZKHNR, TMPTEXT FROM ZEKERHEID, SESSION.TEMPLOA 
         WHERE ZKHRELID = TMPRELID AND ZKHACTSRTCD = TMPACTSRTCD AND ZKHNR = TMPZKHNR) AS ZKH
  ON OPM.ZHORELID = ZKH.ZKHRELID AND OPM.ZHOACTSRTCD = ZKH.ZKHACTSRTCD AND OPM.ZHONR = ZKH.ZKHNR
  WHEN MATCHED
    THEN UPDATE SET OPM.ZHOMUTDATTIJD = CURRENT TIMESTAMP
  WHEN NOT MATCHED
    THEN INSERT(ZHORELID, ZHOACTSRTCD, ZHONR, ZHOTEXT, ZHOINGDAT, ZHOEINDDAT, ZHOMUTDATTIJD, ZHOMUTUSER, ZHOMUTVOLGNR)
       VALUES(ZKH.ZKHRELID, ZKH.ZKHACTSRTCD, ZKH.ZKHNR, ZKH.TMPTEXT, CURRENT DATE, '9999-12-31', CURRENT TIMESTAMP, 'SYSTEM', 0)
  ELSE IGNORE
) AS TINUS;

COMMIT;
