CREATE TABLE S_BD_REKENING2 (
       IBAN_BELASTINGDIENST          CHAR(42)        NOT NULL,
       DT_GELDIG_VAN                 DATE            NOT NULL,
       DT_GELDIG_TM                  DATE            NOT NULL,
       FIN_BANKREK_TYPE              CHAR(3)         NOT NULL,
       FIN_BANKREK_OMSCHRIJVING      VARCHAR(70)     NOT NULL,
       -- VOLLEDIG VERWERKTE RAPPORT
       ACTUEEL_VOLGNR_RAPPORT        DECIMAL(5 , 0)  NOT NULL,
       ACTUEEL_DT_PERIODE_VANAF      TIMESTAMP       NOT NULL,
       ACTUEEL_DT_PERIODE_TOTMET     TIMESTAMP       NOT NULL,
       -- NIEUW NOG TE VERWERKEN (NULL INDIEN VERWERKT)
       NIEUW_VOLGNR_RAPPORT          DECIMAL(5 , 0)  WITH DEFAULT NULL,
       NIEUW_DT_PERIODE_VANAF        TIMESTAMP       WITH DEFAULT NULL,
       NIEUW_DT_PERIODE_TOTMET       TIMESTAMP       WITH DEFAULT NULL,
       TENNAAM_BELASTINGDIENST       VARCHAR(70)     NOT NULL,
       BIC_BANK_BELASTINGDIENST      VARCHAR(11)     NOT NULL,
       UID_UPDATED                   CHAR(7)         NOT NULL,
       -- NIET APPLICATIEF:
       TS_UPDATED                    TIMESTAMP       NOT NULL
                                     GENERATED ALWAYS
                                     FOR EACH ROW ON UPDATE
                                     AS ROW CHANGE TIMESTAMP,
       -- VERSIE TBV OPTIMISTIC LOCKING DOOR JAVA-FRAMEWORK
       -- ENKEL TBV BEHEERAPP, DUS HOEFT NIET IN INDEX
       VERSIE                        INTEGER         NOT NULL
                                                     WITH DEFAULT 0 ,
       SOORT_REKENING                VARCHAR(10)     WITH DEFAULT NULL,
       PERIOD BUSINESS_TIME (DT_GELDIG_VAN, DT_GELDIG_TM),
       CONSTRAINT   PRIM_S_BD_REKENING
            PRIMARY KEY (IBAN_BELASTINGDIENST
                        ,BUSINESS_TIME WITHOUT OVERLAPS)
       )
  AUDIT  NONE
  DATA   CAPTURE CHANGES
  CCSID  UNICODE
  NOT    VOLATILE
  APPEND NO ;
