CREATE SEQUENCE OPBERGNR_NOODPROC_SEQ
  MINVALUE 500000
  MAXVALUE 999999
  START WITH 500000
  INCREMENT BY 1
  NOCACHE
  NOCYCLE
  ORDER;

ALTER SEQUENCE OPBERGNR_NOODPROC_SEQ
  NOCACHE
  NOCYCLE
  ;
