DROP TRIGGER DPLE01.BEVINDING_INSERT;

--#SET TERMINATOR @

CREATE TRIGGER ABAE01.MEDEWERKERSGEBRUIKMONITORING_UPDATE_TR
  AFTER UPDATE ON ABAM_MEDE_MEDEWERKERSGEBRUIKEVENT
  REFERENCING NEW AS MEDEWERKERSGEBRUIKEVENT
  FOR EACH ROW
  MODE DB2SQL
    BEGIN ATOMIC
      CALL SDZ.SDFDB2(CONCAT('"SSDFDB2TOKEN":"SDFDB2ABA02Index"', CONCAT('{', CONCAT(MEDEWERKERSGEBRUIKEVENT.METING, '}'))));
    END @


