SET CURRENT SQLID = DBAE01;
SET SCHEMA DBAE01;
-- MET DEZE SELECT WORDT DE FUNCTION DBADFN03 GESELCTEERD  
-- DIE VERVOLGENS EEN CALL DOET NAAR DE PROCEDURE DBADSP03 
                                                           
SELECT DBAE01.DBADFN03() FROM SYSIBM.SYSDUMMY1;    
