CREATE TABLE LOG_KE_MESSAGES
    (KMS_ID               BIGINT         NOT NULL,
     mMS_MESSAGE_TXT      VARCHAR(4090)  NOT NULL FOR MIXED DATA,
     KMS_REGISTR_DTT      TIMESTAMP      NOT NULL,
     KMS_TASKSERVICE      VARCHAR(256)   NOT NULL,
     CONSTRAINT       KMS_ID
        PRIMARY KEY  (KMS_ID)
    )
     IN RLHDB01.RLHTSKMS
     AUDIT NONE
     DATA CAPTURE CHANGES
     CCSID      UNICODE
     NOT VOLATILE
     APPEND YES ;
