SET CURRENT SQLID = AHME01;
SET SCHEMA AHME01;
------------------------------------------------------------------------
-- Begin stored procedure voor het cyclisch wisselen van de partities
-- van de splunk-tabel
--
------------------------------------------------------------------------
--
------------------------------------------------------------------------
--    Stored procedure=AHMRTPTN
------------------------------------------------------------------------
--
--
--#SET TERMINATOR @
--
--
CREATE PROCEDURE AHMRTPTN(IN P_JAAR INTEGER,
                          IN P_MAAND INTEGER) VERSION V1
     LANGUAGE SQL
     NOT DETERMINISTIC
     MODIFIES SQL DATA
     CALLED ON NULL INPUT
     DYNAMIC RESULT SETS 0
     ALLOW DEBUG MODE
     PARAMETER CCSID EBCDIC
     QUALIFIER AHME01
    PACKAGE OWNER AHME
    ASUTIME NO LIMIT
    COMMIT ON RETURN NO
    INHERIT SPECIAL REGISTERS
    WLM ENVIRONMENT FOR DEBUG MODE DB2USP00
    NODEFER PREPARE
    CURRENT DATA NO
    DEGREE 1
    DYNAMICRULES RUN
    WITH EXPLAIN
    WITHOUT IMMEDIATE WRITE
    ISOLATION LEVEL CS
    WITHOUT KEEP DYNAMIC
    OPTHINT ''
    RELEASE AT COMMIT
    P1:
BEGIN
CASE P_JAAR
         WHEN 2019 THEN
           IF P_MAAND = 1 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2019-01-31') RESET;
END IF ;
           IF
P_MAAND = 2 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2019-02-28') RESET;
END IF ;
           IF
P_MAAND = 3 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2019-03-31') RESET;
END IF ;
           IF
P_MAAND = 4 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2019-04-30') RESET;
END IF ;
           IF
P_MAAND = 5 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2019-05-31') RESET;
END IF ;
           IF
P_MAAND = 6 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2019-06-30') RESET;
END IF ;
           IF
P_MAAND = 7 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2019-07-31') RESET;
END IF ;
           IF
P_MAAND = 8 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2019-08-31') RESET;
END IF ;
           IF
P_MAAND = 9 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2019-09-30') RESET;
END IF ;
           IF
P_MAAND = 10 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2019-10-31') RESET;
END IF ;
           IF
P_MAAND = 11 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2019-11-30') RESET;
END IF ;
           IF
P_MAAND = 12 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2019-12-31') RESET;
END IF ;
WHEN 2020 THEN
           IF P_MAAND = 1 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2020-01-31') RESET;
END IF ;
           IF
P_MAAND = 2 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2020-02-29') RESET;
END IF ;
           IF
P_MAAND = 3 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2020-03-31') RESET;
END IF ;
           IF
P_MAAND = 4 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2020-04-30') RESET;
END IF ;
           IF
P_MAAND = 5 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2020-05-31') RESET;
END IF ;
           IF
P_MAAND = 6 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2020-06-30') RESET;
END IF ;
           IF
P_MAAND = 7 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2020-07-31') RESET;
END IF ;
           IF
P_MAAND = 8 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2020-08-31') RESET;
END IF ;
           IF
P_MAAND = 9 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2020-09-30') RESET;
END IF ;
           IF
P_MAAND = 10 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2020-10-31') RESET;
END IF ;
           IF
P_MAAND = 11 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2020-11-30') RESET;
END IF ;
           IF
P_MAAND = 12 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2020-12-31') RESET;
END IF ;
WHEN 2021 THEN
           IF P_MAAND = 1 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2021-01-31') RESET;
END IF ;
           IF
P_MAAND = 2 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2021-02-28') RESET;
END IF ;
           IF
P_MAAND = 3 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2021-03-31') RESET;
END IF ;
           IF
P_MAAND = 4 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2021-04-30') RESET;
END IF ;
           IF
P_MAAND = 5 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2021-05-31') RESET;
END IF ;
           IF
P_MAAND = 6 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2021-06-30') RESET;
END IF ;
           IF
P_MAAND = 7 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2021-07-31') RESET;
END IF ;
           IF
P_MAAND = 8 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2021-08-31') RESET;
END IF ;
           IF
P_MAAND = 9 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2021-09-30') RESET;
END IF ;
           IF
P_MAAND = 10 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2021-10-31') RESET;
END IF ;
           IF
P_MAAND = 11 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2021-11-30') RESET;
END IF ;
           IF
P_MAAND = 12 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2021-12-31') RESET;
END IF ;
WHEN 2022 THEN
           IF P_MAAND = 1 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2022-01-31') RESET;
END IF ;
           IF
P_MAAND = 2 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2022-02-28') RESET;
END IF ;
           IF
P_MAAND = 3 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2022-03-31') RESET;
END IF ;
           IF
P_MAAND = 4 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2022-04-30') RESET;
END IF ;
           IF
P_MAAND = 5 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2022-05-31') RESET;
END IF ;
           IF
P_MAAND = 6 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2022-06-30') RESET;
END IF ;
           IF
P_MAAND = 7 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2022-07-31') RESET;
END IF ;
           IF
P_MAAND = 8 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2022-08-31') RESET;
END IF ;
           IF
P_MAAND = 9 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2022-09-30') RESET;
END IF ;
           IF
P_MAAND = 10 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2022-10-31') RESET;
END IF ;
           IF
P_MAAND = 11 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2022-11-30') RESET;
END IF ;
           IF
P_MAAND = 12 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2022-12-31') RESET;
END IF ;
WHEN 2023 THEN
           IF P_MAAND = 1 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2023-01-31') RESET;
END IF ;
           IF
P_MAAND = 2 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2023-02-28') RESET;
END IF ;
           IF
P_MAAND = 3 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2023-03-31') RESET;
END IF ;
           IF
P_MAAND = 4 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2023-04-30') RESET;
END IF ;
           IF
P_MAAND = 5 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2023-05-31') RESET;
END IF ;
           IF
P_MAAND = 6 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2023-06-30') RESET;
END IF ;
           IF
P_MAAND = 7 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2023-07-31') RESET;
END IF ;
           IF
P_MAAND = 8 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2023-08-31') RESET;
END IF ;
           IF
P_MAAND = 9 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2023-09-30') RESET;
END IF ;
           IF
P_MAAND = 10 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2023-10-31') RESET;
END IF ;
           IF
P_MAAND = 11 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2023-11-30') RESET;
END IF ;
           IF
P_MAAND = 12 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2023-12-31') RESET;
END IF ;
WHEN 2024 THEN
           IF P_MAAND = 1 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2024-01-31') RESET;
END IF ;
           IF
P_MAAND = 2 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2024-02-29') RESET;
END IF ;
           IF
P_MAAND = 3 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2024-03-31') RESET;
END IF ;
           IF
P_MAAND = 4 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2024-04-30') RESET;
END IF ;
           IF
P_MAAND = 5 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2024-05-31') RESET;
END IF ;
           IF
P_MAAND = 6 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2024-06-30') RESET;
END IF ;
           IF
P_MAAND = 7 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2024-07-31') RESET;
END IF ;
           IF
P_MAAND = 8 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2024-08-31') RESET;
END IF ;
           IF
P_MAAND = 9 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2024-09-30') RESET;
END IF ;
           IF
P_MAAND = 10 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2024-10-31') RESET;
END IF ;
           IF
P_MAAND = 11 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2024-11-30') RESET;
END IF ;
           IF
P_MAAND = 12 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2024-12-31') RESET;
END IF ;
WHEN 2025 THEN
           IF P_MAAND = 1 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2025-01-31') RESET;
END IF ;
           IF
P_MAAND = 2 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2025-02-28') RESET;
END IF ;
           IF
P_MAAND = 3 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2025-03-31') RESET;
END IF ;
           IF
P_MAAND = 4 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2025-04-30') RESET;
END IF ;
           IF
P_MAAND = 5 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2025-05-31') RESET;
END IF ;
           IF
P_MAAND = 6 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2025-06-30') RESET;
END IF ;
           IF
P_MAAND = 7 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2025-07-31') RESET;
END IF ;
           IF
P_MAAND = 8 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2025-08-31') RESET;
END IF ;
           IF
P_MAAND = 9 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2025-09-30') RESET;
END IF ;
           IF
P_MAAND = 10 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2025-10-31') RESET;
END IF ;
           IF
P_MAAND = 11 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2025-11-30') RESET;
END IF ;
           IF
P_MAAND = 12 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2025-12-31') RESET;
END IF ;
WHEN 2026 THEN
           IF P_MAAND = 1 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2026-01-31') RESET;
END IF ;
           IF
P_MAAND = 2 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2026-02-28') RESET;
END IF ;
           IF
P_MAAND = 3 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2026-03-31') RESET;
END IF ;
           IF
P_MAAND = 4 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2026-04-30') RESET;
END IF ;
           IF
P_MAAND = 5 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2026-05-31') RESET;
END IF ;
           IF
P_MAAND = 6 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2026-06-30') RESET;
END IF ;
           IF
P_MAAND = 7 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2026-07-31') RESET;
END IF ;
           IF
P_MAAND = 8 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2026-08-31') RESET;
END IF ;
           IF
P_MAAND = 9 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2026-09-30') RESET;
END IF ;
           IF
P_MAAND = 10 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2026-10-31') RESET;
END IF ;
           IF
P_MAAND = 11 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2026-11-30') RESET;
END IF ;
           IF
P_MAAND = 12 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2026-12-31') RESET;
END IF ;
WHEN 2027 THEN
           IF P_MAAND = 1 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2027-01-31') RESET;
END IF ;
           IF
P_MAAND = 2 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2027-02-28') RESET;
END IF ;
           IF
P_MAAND = 3 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2027-03-31') RESET;
END IF ;
           IF
P_MAAND = 4 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2027-04-30') RESET;
END IF ;
           IF
P_MAAND = 5 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2027-05-31') RESET;
END IF ;
           IF
P_MAAND = 6 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2027-06-30') RESET;
END IF ;
           IF
P_MAAND = 7 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2027-07-31') RESET;
END IF ;
           IF
P_MAAND = 8 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2027-08-31') RESET;
END IF ;
           IF
P_MAAND = 9 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2027-09-30') RESET;
END IF ;
           IF
P_MAAND = 10 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2027-10-31') RESET;
END IF ;
           IF
P_MAAND = 11 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2027-11-30') RESET;
END IF ;
           IF
P_MAAND = 12 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2027-12-31') RESET;
END IF ;
WHEN 2028 THEN
           IF P_MAAND = 1 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2028-01-31') RESET;
END IF ;
           IF
P_MAAND = 2 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2028-02-29') RESET;
END IF ;
           IF
P_MAAND = 3 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2028-03-31') RESET;
END IF ;
           IF
P_MAAND = 4 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2028-04-30') RESET;
END IF ;
           IF
P_MAAND = 5 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2028-05-31') RESET;
END IF ;
           IF
P_MAAND = 6 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2028-06-30') RESET;
END IF ;
           IF
P_MAAND = 7 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2028-07-31') RESET;
END IF ;
           IF
P_MAAND = 8 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2028-08-31') RESET;
END IF ;
           IF
P_MAAND = 9 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2028-09-30') RESET;
END IF ;
           IF
P_MAAND = 10 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2028-10-31') RESET;
END IF ;
           IF
P_MAAND = 11 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2028-11-30') RESET;
END IF ;
           IF
P_MAAND = 12 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2028-12-31') RESET;
END IF ;
WHEN 2029 THEN
           IF P_MAAND = 1 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2029-01-31') RESET;
END IF ;
           IF
P_MAAND = 2 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2029-02-28') RESET;
END IF ;
           IF
P_MAAND = 3 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2029-03-31') RESET;
END IF ;
           IF
P_MAAND = 4 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2029-04-30') RESET;
END IF ;
           IF
P_MAAND = 5 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2029-05-31') RESET;
END IF ;
           IF
P_MAAND = 6 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2029-06-30') RESET;
END IF ;
           IF
P_MAAND = 7 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2029-07-31') RESET;
END IF ;
           IF
P_MAAND = 8 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2029-08-31') RESET;
END IF ;
           IF
P_MAAND = 9 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2029-09-30') RESET;
END IF ;
           IF
P_MAAND = 10 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2029-10-31') RESET;
END IF ;
           IF
P_MAAND = 11 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2029-11-30') RESET;
END IF ;
           IF
P_MAAND = 12 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2029-12-31') RESET;
END IF ;
WHEN 2030 THEN
           IF P_MAAND = 1 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2030-01-31') RESET;
END IF ;
           IF
P_MAAND = 2 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2030-02-28') RESET;
END IF ;
           IF
P_MAAND = 3 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2030-03-31') RESET;
END IF ;
           IF
P_MAAND = 4 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2030-04-30') RESET;
END IF ;
           IF
P_MAAND = 5 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2030-05-31') RESET;
END IF ;
           IF
P_MAAND = 6 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2030-06-30') RESET;
END IF ;
           IF
P_MAAND = 7 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2030-07-31') RESET;
END IF ;
           IF
P_MAAND = 8 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2030-08-31') RESET;
END IF ;
           IF
P_MAAND = 9 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2030-09-30') RESET;
END IF ;
           IF
P_MAAND = 10 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2030-10-31') RESET;
END IF ;
           IF
P_MAAND = 11 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2030-11-30') RESET;
END IF ;
           IF
P_MAAND = 12 THEN
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT
    ('2030-12-31') RESET;
END IF ;
ELSE
ALTER TABLE SPLUNK ROTATE PARTITION FIRST TO LAST ENDING AT (
    '2050-12-31') RESET;
END
CASE ;
END P1
@
--
--#SET TERMINATOR ;
--
------------------------------------------------------------------------
-- Einde stored procedure
------------------------------------------------------------------------
GRANT
EXECUTE
ON
PROCEDURE
AHMRTPTN
TO
$EAHM00;
--
COMMIT;
--
------------------------------------------------------------------------
--
--

