-- both working
GRANT EXECUTE ON PACKAGE "A_REST_COLLID".APACKAGE TO AUSER;
GRANT EXECUTE ON PACKAGE A_REST_COLLID."APACKAGE" TO AUSER;
-- one that doesn't
GRANT EXECUTE ON PACKAGE "A_REST_COLLID"."APACKAGE" TO AUSER;
